export const data = [
  { id: '1', title: 'Explore the Unknown', image: require('../assets/images/headerimg1.jpg') },
  { id: '2', title: 'A Journey Beyond', image: require('../assets/images/headerimg2.jpg') },
  { id: '3', title: 'Unveiling the Mystery', image: require('../assets/images/headerimg3.jpg') },
  { id: '4', title: 'Lost in the Moment', image: require('../assets/images/headerimg4.jpg') },
  { id: '5', title: 'Chasing the Horizon', image: require('../assets/images/headerimg5.jpg') },
];

export const categories = [
  {
    id: "1",
    category: "Phones",
    name: "iPhone 14 Pro",
    price: 1099,
    image: require('../assets/images/iphone14.jpg'),
    description: "6.1-inch display, A16 Bionic chip, 48MP camera.",
    rating: 4.8,
  },
  {
    id: "2",
    category: "Laptops",
    name: "MacBook Pro M2",
    price: 1999,
    image: require('../assets/images/MacBookProM2.jpg'),
    description: "M2 chip, 16GB RAM, 512GB SSD, Retina display.",
    rating: 4.9,
  },
  {
    id: "3",
    category: "Gaming",
    name: "PlayStation 5",
    price: 499,
    image: require('../assets/images/PlayStation5.jpeg'),
    description: "8K support, ultra-fast SSD, adaptive triggers.",
    rating: 4.9,
  },
  {
    id: "4",
    category: "Audio Devices",
    name: "Sony WH-1000XM5",
    price: 399,
    image: require('../assets/images/SonyWH-1000XM5.jpeg'),
    description: "Industry-leading noise cancellation, 30-hour battery life.",
    rating: 4.9,
  },
  {
    id: "5",
    category: "Home Appliances",
    name: "Samsung Smart Refrigerator",
    price: 2999,
    image: require('../assets/images/SamsungSmartRefrigerator.jpeg'),
    description: "AI-powered cooling, touchscreen display, voice control.",
    rating: 4.9,
  },
  {
    id: "6",
    category: "Smartwatches",
    name: "Apple Watch Ultra",
    price: 799,
    image: require('../assets/images/AppleWatchUltra.jpeg'),
    description: "49mm case, rugged design, 36-hour battery life.",
    rating: 4.8,
  }


]


export const products = [
  {
    id: "1",
    category: "Phones",
    name: "iPhone 14 Pro",
    price: 1099,
    image: require('../assets/images/iphone14.jpg'),
    description: "The iPhone 14 Pro features a 6.1-inch Super Retina XDR display with ProMotion technology for a faster, more responsive feel. Powered by the A16 Bionic chip, it ensures seamless performance and efficiency. The new 48MP main camera delivers stunning photos and videos, while the improved battery life keeps you connected longer.",
    rating: 4.8,
  },
  {
    id: "2",
    category: "Phones",
    name: "Samsung Galaxy S23 Ultra",
    price: 1199,
    image: require('../assets/images/SamsungS23 Ultra.jpg'),
    description: "The Samsung Galaxy S23 Ultra boasts a 6.8-inch Dynamic AMOLED display with a 120Hz refresh rate for smooth scrolling. Equipped with the latest Snapdragon 8 Gen 2 processor, it offers top-tier performance. The groundbreaking 200MP camera system captures ultra-high-resolution photos, and the 5000mAh battery ensures extended usage.",
    rating: 4.7,
  },
  {
    id: "3",
    category: "Phones",
    name: "Google Pixel 7 Pro",
    price: 899,
    image: require('../assets/images/GooglePixel.jpg'),
    description: "The Google Pixel 7 Pro comes with a 6.7-inch OLED display and is powered by the advanced Tensor G2 chip, delivering smooth and efficient performance. Its 50MP main camera, combined with Google's computational photography, ensures stunning photos in any lighting condition. The device also offers a clean Android experience with timely updates.",
    rating: 4.6,
  },
  {
    id: "4",
    category: "Phones",
    name: "OnePlus 11",
    price: 699,
    image: require('../assets/images/OnePlus11.jpg'),
    description: "The OnePlus 11 features a 6.7-inch Fluid AMOLED display with a 120Hz refresh rate. Powered by the Snapdragon 8 Gen 2 processor, it ensures swift performance. The 5000mAh battery supports fast charging, and the triple-camera setup provides versatile photography options.",
    rating: 4.5,
  },

  // 💻 Laptops
  {
    id: "5",
    category: "Laptops",
    name: "MacBook Pro M2",
    price: 1999,
    image: require('../assets/images/MacBookProM2.jpg'),
    description: "The MacBook Pro M2 is equipped with Apple's latest M2 chip, offering significant performance improvements over its predecessor. It features a 16-inch Retina display with True Tone technology, 16GB of unified memory, and a 512GB SSD for fast storage. The laptop also boasts an improved thermal system for sustained performance.",
    rating: 4.9,
  },
  {
    id: "6",
    category: "Laptops",
    name: "Dell XPS 15",
    price: 1899,
    image: require('../assets/images/DellXPS15.avif'),
    description: "The Dell XPS 15 offers a 15.6-inch 4K OLED display, providing vibrant and accurate colors. Powered by an Intel i9 processor and 32GB RAM, it handles demanding tasks with ease. The 1TB SSD ensures ample storage and quick data access, making it ideal for professionals and creatives.",
    rating: 4.6,
  },
  {
    id: "7",
    category: "Laptops",
    name: "HP Spectre x360",
    price: 1599,
    image: require('../assets/images/HPSpectrex360.jpeg'),
    description: "The HP Spectre x360 is a versatile 2-in-1 laptop with a 13.3-inch 4K touchscreen display. It features an Intel i7 processor, 16GB RAM, and a 1TB SSD. The 360-degree hinge allows for seamless transitions between laptop and tablet modes, catering to various user needs.",
    rating: 4.7,
  },
  {
    id: "8",
    category: "Laptops",
    name: "Lenovo ThinkPad X1 Carbon",
    price: 1699,
    image: require('../assets/images/LenovoThinkPad X1Carbon.jpeg'),
    description: "The Lenovo ThinkPad X1 Carbon is an ultra-lightweight laptop designed for business professionals. It features a 14-inch Full HD display, Intel i7 processor, 32GB RAM, and a 1TB SSD. The laptop also offers robust security features and long battery life, ensuring productivity on the go.",
    rating: 4.8,
  },

  // 🎮 Gaming
  {
    id: "9",
    category: "Gaming",
    name: "PlayStation 5",
    price: 499,
    image: require('../assets/images/PlayStation5.jpeg'),
    description: "The PlayStation 5 offers a transformative gaming experience with 8K support and ultra-fast SSD for reduced load times. Its adaptive triggers and haptic feedback provide immersive gameplay, while the extensive game library caters to diverse gaming preferences.",
    rating: 4.9,
  },
  {
    id: "10",
    category: "Gaming",
    name: "Xbox Series X",
    price: 499,
    image: require('../assets/images/XboxSeries.jpeg'),
    description: "The Xbox Series X delivers 12 teraflops of processing power, enabling 4K gaming at up to 120 frames per second. Its quick resume feature allows players to switch between games seamlessly, and the backward compatibility ensures access to a vast collection of titles.",
    rating: 4.8,
  },
  {
    id: "11",
    category: "Gaming",
    name: "Nintendo Switch OLED",
    price: 349,
    image: require('../assets/images/NintendoSwitchOLED.jpeg'),
    description: "The Nintendo Switch OLED model features a 7-inch OLED screen, providing vibrant visuals in handheld mode. Its versatile design allows for handheld, tabletop, and docked play, catering to various gaming scenarios. The enhanced audio and adjustable stand improve the overall gaming experience.",
    rating: 4.7,
  },

  {
    id: "13",
    category: "Smartwatches",
    name: "Samsung Galaxy Watch 5 Pro",
    price: 449,
    image: require('../assets/images/SamsungGalaxyWatch5Pro.jpeg'),
    description: "The Samsung Galaxy Watch 5 Pro features a stunning 1.4-inch AMOLED display with Always-On functionality, advanced ECG and blood pressure monitoring, and an impressive 80-hour battery life. It is built with sapphire crystal glass and a titanium case for durability",
    rating: 4.6,
  },

  {
    id: "14",
    category: "Cameras",
    name: "Sony A7 IV",
    price: 2499,
    image: require('../assets/images/SonyA7IV.jpeg'),
    description: "The Sony A7 IV is a professional-grade mirrorless camera featuring a high-resolution 33MP full-frame sensor, 4K 60fps video recording, and advanced autofocus with real-time tracking. It supports 10-bit color depth, making it perfect for both photographers and videographers looking for exceptional image quality and dynamic range.",
    rating: 4.9,
  },
  {
    id: "15",
    category: "Cameras",
    name: "Canon EOS R6",
    price: 2399,
    image: require('../assets/images/CanonEOSR6.jpeg'),
    description: "Designed for enthusiasts and professionals alike, the Canon EOS R6 features a 20MP full-frame sensor with Dual Pixel Autofocus for incredibly sharp and fast focusing. It supports 4K video recording at 60fps, in-body image stabilization, and superb low-light performance, making it an excellent choice for both photography and videography.",
    rating: 4.7,
  },

  {
    id: "16",
    category: "Home Appliances",
    name: "Dyson V15 Detect Vacuum",
    price: 699,
    image: require('../assets/images/DysonV15DetectVacuum.jpeg'),
    description: "The Dyson V15 Detect is a cutting-edge cordless vacuum cleaner equipped with laser dust detection technology, allowing it to reveal hidden dust particles on hard floors. With powerful suction, an intelligent LCD display that provides real-time performance updates, and up to 60 minutes of runtime, it offers an unmatched cleaning experience.",
    rating: 4.8,
  },

  {
    id: "17",
    category: "Home Appliances",
    name: "Samsung Smart Refrigerator",
    price: 2999,
    image: require('../assets/images/SamsungSmartRefrigerator.jpeg'),
    description: "This AI-powered smart refrigerator features an intuitive touchscreen display, voice control integration, and customizable cooling zones. It offers WiFi connectivity for remote management, an energy-efficient design, and a sleek stainless steel finish. Perfect for modern kitchens, it keeps food fresher for longer while enhancing convenience.",
    rating: 4.9,
  },

  // 🎧 Audio Devices
  {
    id: "18",
    category: "Audio Devices",
    name: "Sony WH-1000XM5",
    price: 399,
    image: require('../assets/images/SonyWH-1000XM5.jpeg'),
    description: "Experience industry-leading noise cancellation with dual processors and adaptive sound control. The Sony WH-1000XM5 offers up to 30 hours of battery life, crystal-clear hands-free calling, and high-resolution audio with LDAC support. Its lightweight design and plush ear cushions ensure maximum comfort for extended use.",
    rating: 4.8,
  },
  {
    id: "19",
    category: "Audio Devices",
    name: "Bose QuietComfort 45",
    price: 329,
    image: require('../assets/images/BoseQuietComfort45.jpeg'),
    description: "The Bose QuietComfort 45 headphones deliver superior active noise cancellation with adjustable ambient modes. Featuring a lightweight and ergonomic design, they offer up to 24 hours of wireless playback, clear voice pickup for calls.",
    rating: 4.7,
  },
  {
    id: "20",
    category: "Audio Devices",
    name: "JBL Charge 5",
    price: 179,
    image: require('../assets/images/JBLCharge5.jpeg'),
    description: "A rugged, waterproof Bluetooth speaker designed for adventure. The JBL Charge 5 delivers powerful, immersive sound with JBL Pro Sound technology and dual bass radiators. With up to 20 hours of battery life, a built-in power bank, and PartyBoost compatibility, it's the ultimate portable speaker for any occasion.",
    rating: 4.6,
  }
]
